services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./php/src:/var/www/html/
    ports:
        - 8080:80
  db:
    container_name: MySQL
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - volumen_MySQL:/var/lib/mysql
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8085:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
volumes:
  volumen_MySQL: